language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - nightly

services:
    - redis

sudo: required
dist: bionic
group: edge

addons:
    mariadb: '10.2'
    hosts:
        - misp.local
        - localhost

env:
    global:
        - UNATTENDED=1
        - MISP_USER=travis

before_install:
    - git config --global user.name "TravisCI"
    - export PATH="$HOME/.local/bin:$PATH"

install:
    - bash ./INSTALL/INSTALL.sh -C
    - bash ./INSTALL/INSTALL.sh -A -u

before_script:
    - curl http://misp.local
    - AUTH=`cat key.txt`
    - sudo chmod -R 777 PyMISP
    - pushd PyMISP
    - echo 'url = "http://misp.local"' >> tests/keys.py
    - echo 'key = "'${AUTH}'"' >> tests/keys.py
    - cat tests/keys.py
    - popd

script:
    - pushd tests
    - ./curl_tests.sh $AUTH
    - popd
    - pushd PyMISP
    # FIXME: should be install, but as lief is changing all the time, we have to use update instead: https://github.com/MISP/PyMISP/issues/391
    - pipenv update -d
    - pushd tests
    - git clone https://github.com/viper-framework/viper-test-files.git
    - popd
    - pipenv run python tests/test.py
    - pipenv run python tests/test_mispevent.py
    - pipenv run python tests/test_offline.py
    - pipenv run python tests/testlive_comprehensive.py
    - popd
    - cp PyMISP/tests/keys.py PyMISP/examples/events/
    - pushd PyMISP/examples/events/
    - pipenv run python ./create_massive_dummy_events.py -l 5 -a 30
    - popd
    - pushd app/files/feed-metadata
    - jsonschema -i defaults.json schema.json
    - popd

after_failure:
    - curl http://misp.local
    - cat /etc/apache2/sites-available/misp.local.conf
    - sudo ls -l /var/log/apache2
    - sudo cat `pwd`/app/tmp/logs/error.log
    - sudo cat `pwd`/app/tmp/logs/debug.log
    - sudo cat /var/log/apache2/error.log
    - sudo cat /var/log/apache2/misp.local_error.log
    - sudo cat /var/log/apache2/misp.local_access.log
    - pwd

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/05e30284086a8e948d31
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

after_success:
    - coveralls
    - coverage report
    - coverage xml
    - codecov
